### PR TITLE
parallel dataset discovery (cloud speedup)

### PR DESCRIPTION
**Pull request by axtimwalde**
Removes the nicer looking but non parallel and therefore too slow discovery in the base branch, sorry.  Also reintroduces discovery of multi-scale datasets without the attribute (which I find useful because I have many).

### CODE REVIEW

**Comment by axtimwalde** [comment]
typos can be fixed at squash time ;)

**Comment by hanslovsky** [comment]
Do we need a SNAPSHOT version of n5-google-cloud or will 2.3.1. release do?

**Comment by axtimwalde** [comment]
@hanslovsky I just pushed a change to n5-google-cloud that is a useful speedup, but works with release version.

**Comment by hanslovsky** [comment]
I think I understand the changes and it looks good to me. The only change I made is create `ExecutorService`s with daemon threads instead of user threads. I will merge this and use the n5-google-cloud SNAPSHOT dependency as in your PR. There is many other SNAPSHOT dependencies that still wait for a PR/merge/release of master, so it won't hurt to have one more.

**Comment by axtimwalde** [comment]
the merge un-fixed multi-scale dataset discovery

**Comment by hanslovsky** [comment]
What do you mean? I can see it both on
 * [hanslovsky/bigcat:multiscale-painting](https://github.com/hanslovsky/bigcat/blob/multiscale-painting/src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/N5Helpers.java#L200-L213), and
 * [saalfeldlab/paintera:master](https://github.com/saalfeldlab/paintera/blob/master/src/main/java/org/janelia/saalfeldlab/paintera/ui/opendialog/N5Helpers.java#L200-L213)

**Comment by hanslovsky** [comment]
As [gitter](https://gitter.im/scenerygraphics/hackathon_moscow_2018?at=5ae37acbdad6fb186ff402e2) reveals, this was just an issue of a delayed merge into paintera:master. Should be resolved now!

**Comment by axtimwalde** [comment]
Perfect. Thanks!

**Pull request merged**
